### ISSUE TITLE
examples/getSupplyAda.js returns an error 

### ISSUE THREAD

**Issue by developeron29** [coinranking/supplies#689]
When i run examples/[getSupplyAda.js](https://github.com/coinranking/supplies/blob/master/examples/getSupplyAda.js)

it returns this error- > (node:4558) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cgsRedeemedAmountTotal' of undefined

![Screenshot 2022-11-01 at 3 58 53 PM](https://user-images.githubusercontent.com/4932001/199213705-24fc9e09-ee5d-40c1-8b5b-2bd14484f55a.png)

**Comment by wouthoekstra** [comment]
Thank you for for finding this issue. Cardanoexplorer.com seems to be permanently down. We will have to decide upon a new block explorer to list to get the supplies for Cardano.

**Comment by wouthoekstra** [comment]
We have removed the driver in https://github.com/coinranking/supplies/pull/703
