### ISSUE TITLE
examples/getSupplyDash.js returns an error

### ISSUE THREAD

**Issue by developeron29** [coinranking/supplies#690]
examples/[getSupplyDash.js](https://github.com/coinranking/supplies/blob/master/examples/getSupplyDash.js) returns this error > (node:4919) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'blockchain' of 'undefined' as it is undefined.

![Screenshot 2022-11-01 at 4 20 44 PM](https://user-images.githubusercontent.com/4932001/199217179-4915c3c4-698e-448e-97e6-09030ac5b297.png)

**Comment by wouthoekstra** [comment]
Thank you for noticing. The example file had an error, which is fixed here: https://github.com/coinranking/supplies/pull/696
