### ISSUE TITLE
examples/getSupplyEtc.js  returns an error

### ISSUE THREAD

**Issue by developeron29** [coinranking/supplies#692]
[examples](https://github.com/coinranking/supplies/tree/master/examples)/getSupplyEtc.js returns this error

(node:5110) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - {"errorcode":500,"errormessage":"parsing supply value from database"}

![Screenshot 2022-11-01 at 4 25 41 PM](https://user-images.githubusercontent.com/4932001/199218039-8258d804-9084-4de5-b870-b30d2492cad3.png)

**Comment by wouthoekstra** [comment]
Diadata does not list Ethereum Classic anymore, we will have to find a new block explorer.

**Comment by wouthoekstra** [comment]
We have removed the driver in https://github.com/coinranking/supplies/pull/703
