### ISSUE TITLE
examples/getSupplyNeo.js returns an error

### ISSUE THREAD

**Issue by everycoinprice** [coinranking/supplies#699]
Hi

(node:817) UnhandledPromiseRejectionWarning: RequestError: Error: getaddrinfo ENOTFOUND seed1.cityofzion.io

error returned on running node examples/getSupplyNeo.js

![Screenshot 2022-11-08 at 9 43 36 AM](https://user-images.githubusercontent.com/101936368/200473618-6023e6d3-fd02-4af5-a30c-bd14a0e2479f.png)

**Comment by mariannegdg** [comment]
Thank you for your input, much appreciated!
To give you an update; this repository used to be one of the sources for the supplies we show on Coinranking. However, even though we still use some of the drivers here, we now primarily use other sources like API endpoints, which we add directly to and within our own system. That means we won't update the drivers here as active anymore... Again thank you for letting us know and we will think about what we're going to do with this repository.

**Comment by wouthoekstra** [comment]
Removed in https://github.com/coinranking/supplies/pull/700
